### ISSUE TITLE
Remove dependency on Giraffe

### ISSUE THREAD

**Issue by Zaid-Ajaj** [dbrattli/Feliz.ViewEngine#1]
Hi @dbrattli, 

It would be awesome if this library didn't depend on Giraffe and instead was a generic Html generating library for F# so it can be used in other contexts where Giraffe isn't used. For example to generate email body as html or to be used from a Nodejs server library

> Suggestion: renaming to Feliz.StaticHtml

**Comment by dbrattli** [comment]
We could "borrow" the [`ViewBuilder`](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/GiraffeViewEngine.fs#L523) from Giraffe. It's not much code, but it's Apache and Feliz is MIT. Feliz.Giraffe is currently MIT.

**Comment by dbrattli** [comment]
Fixed. Now we just need to find a proper name 🤔 Feliz.StaticHtml sounds like HTML files stored in the file system generated by e.g Hugo. So the pages are not static, but just generated server side (or wherever) at runtime. We should now be able to use it within Fable, so even `Feliz.Server` is not accurate either since you might want to use it client size to generate emails etc.

**Comment by Zaid-Ajaj** [comment]
Feliz.ViewEngine sounds great! Awesome work Dag :heart:
